
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AnalysisRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AnalysisRequest
 * 
 */
export type AnalysisRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$AnalysisRequestPayload>

export type AggregateAnalysisRequest = {
  _count: AnalysisRequestCountAggregateOutputType | null
  _min: AnalysisRequestMinAggregateOutputType | null
  _max: AnalysisRequestMaxAggregateOutputType | null
}

export type AnalysisRequestMinAggregateOutputType = {
  id: string | null
  profileUrl: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AnalysisRequestMaxAggregateOutputType = {
  id: string | null
  profileUrl: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AnalysisRequestCountAggregateOutputType = {
  id: number
  profileUrl: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AnalysisRequestMinAggregateInputType = {
  id?: true
  profileUrl?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type AnalysisRequestMaxAggregateInputType = {
  id?: true
  profileUrl?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type AnalysisRequestCountAggregateInputType = {
  id?: true
  profileUrl?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AnalysisRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnalysisRequest to aggregate.
   */
  where?: Prisma.AnalysisRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisRequests to fetch.
   */
  orderBy?: Prisma.AnalysisRequestOrderByWithRelationInput | Prisma.AnalysisRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AnalysisRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AnalysisRequests
  **/
  _count?: true | AnalysisRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AnalysisRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AnalysisRequestMaxAggregateInputType
}

export type GetAnalysisRequestAggregateType<T extends AnalysisRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateAnalysisRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAnalysisRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateAnalysisRequest[P]>
}




export type AnalysisRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnalysisRequestWhereInput
  orderBy?: Prisma.AnalysisRequestOrderByWithAggregationInput | Prisma.AnalysisRequestOrderByWithAggregationInput[]
  by: Prisma.AnalysisRequestScalarFieldEnum[] | Prisma.AnalysisRequestScalarFieldEnum
  having?: Prisma.AnalysisRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AnalysisRequestCountAggregateInputType | true
  _min?: AnalysisRequestMinAggregateInputType
  _max?: AnalysisRequestMaxAggregateInputType
}

export type AnalysisRequestGroupByOutputType = {
  id: string
  profileUrl: string
  status: string
  createdAt: Date
  updatedAt: Date
  _count: AnalysisRequestCountAggregateOutputType | null
  _min: AnalysisRequestMinAggregateOutputType | null
  _max: AnalysisRequestMaxAggregateOutputType | null
}

export type GetAnalysisRequestGroupByPayload<T extends AnalysisRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AnalysisRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AnalysisRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AnalysisRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AnalysisRequestGroupByOutputType[P]>
      }
    >
  >



export type AnalysisRequestWhereInput = {
  AND?: Prisma.AnalysisRequestWhereInput | Prisma.AnalysisRequestWhereInput[]
  OR?: Prisma.AnalysisRequestWhereInput[]
  NOT?: Prisma.AnalysisRequestWhereInput | Prisma.AnalysisRequestWhereInput[]
  id?: Prisma.StringFilter<"AnalysisRequest"> | string
  profileUrl?: Prisma.StringFilter<"AnalysisRequest"> | string
  status?: Prisma.StringFilter<"AnalysisRequest"> | string
  createdAt?: Prisma.DateTimeFilter<"AnalysisRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AnalysisRequest"> | Date | string
}

export type AnalysisRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  profileUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AnalysisRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AnalysisRequestWhereInput | Prisma.AnalysisRequestWhereInput[]
  OR?: Prisma.AnalysisRequestWhereInput[]
  NOT?: Prisma.AnalysisRequestWhereInput | Prisma.AnalysisRequestWhereInput[]
  profileUrl?: Prisma.StringFilter<"AnalysisRequest"> | string
  status?: Prisma.StringFilter<"AnalysisRequest"> | string
  createdAt?: Prisma.DateTimeFilter<"AnalysisRequest"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AnalysisRequest"> | Date | string
}, "id">

export type AnalysisRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  profileUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AnalysisRequestCountOrderByAggregateInput
  _max?: Prisma.AnalysisRequestMaxOrderByAggregateInput
  _min?: Prisma.AnalysisRequestMinOrderByAggregateInput
}

export type AnalysisRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.AnalysisRequestScalarWhereWithAggregatesInput | Prisma.AnalysisRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.AnalysisRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AnalysisRequestScalarWhereWithAggregatesInput | Prisma.AnalysisRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AnalysisRequest"> | string
  profileUrl?: Prisma.StringWithAggregatesFilter<"AnalysisRequest"> | string
  status?: Prisma.StringWithAggregatesFilter<"AnalysisRequest"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AnalysisRequest"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AnalysisRequest"> | Date | string
}

export type AnalysisRequestCreateInput = {
  id?: string
  profileUrl: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AnalysisRequestUncheckedCreateInput = {
  id?: string
  profileUrl: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AnalysisRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisRequestCreateManyInput = {
  id?: string
  profileUrl: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AnalysisRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profileUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AnalysisRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profileUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AnalysisRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profileUrl?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type AnalysisRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profileUrl?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["analysisRequest"]>

export type AnalysisRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profileUrl?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["analysisRequest"]>

export type AnalysisRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profileUrl?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["analysisRequest"]>

export type AnalysisRequestSelectScalar = {
  id?: boolean
  profileUrl?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AnalysisRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "profileUrl" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["analysisRequest"]>

export type $AnalysisRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AnalysisRequest"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    profileUrl: string
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["analysisRequest"]>
  composites: {}
}

export type AnalysisRequestGetPayload<S extends boolean | null | undefined | AnalysisRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload, S>

export type AnalysisRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AnalysisRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AnalysisRequestCountAggregateInputType | true
  }

export interface AnalysisRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AnalysisRequest'], meta: { name: 'AnalysisRequest' } }
  /**
   * Find zero or one AnalysisRequest that matches the filter.
   * @param {AnalysisRequestFindUniqueArgs} args - Arguments to find a AnalysisRequest
   * @example
   * // Get one AnalysisRequest
   * const analysisRequest = await prisma.analysisRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AnalysisRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, AnalysisRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AnalysisRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AnalysisRequestFindUniqueOrThrowArgs} args - Arguments to find a AnalysisRequest
   * @example
   * // Get one AnalysisRequest
   * const analysisRequest = await prisma.analysisRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AnalysisRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AnalysisRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnalysisRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRequestFindFirstArgs} args - Arguments to find a AnalysisRequest
   * @example
   * // Get one AnalysisRequest
   * const analysisRequest = await prisma.analysisRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AnalysisRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, AnalysisRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnalysisRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRequestFindFirstOrThrowArgs} args - Arguments to find a AnalysisRequest
   * @example
   * // Get one AnalysisRequest
   * const analysisRequest = await prisma.analysisRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AnalysisRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AnalysisRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AnalysisRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AnalysisRequests
   * const analysisRequests = await prisma.analysisRequest.findMany()
   * 
   * // Get first 10 AnalysisRequests
   * const analysisRequests = await prisma.analysisRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const analysisRequestWithIdOnly = await prisma.analysisRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AnalysisRequestFindManyArgs>(args?: Prisma.SelectSubset<T, AnalysisRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AnalysisRequest.
   * @param {AnalysisRequestCreateArgs} args - Arguments to create a AnalysisRequest.
   * @example
   * // Create one AnalysisRequest
   * const AnalysisRequest = await prisma.analysisRequest.create({
   *   data: {
   *     // ... data to create a AnalysisRequest
   *   }
   * })
   * 
   */
  create<T extends AnalysisRequestCreateArgs>(args: Prisma.SelectSubset<T, AnalysisRequestCreateArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AnalysisRequests.
   * @param {AnalysisRequestCreateManyArgs} args - Arguments to create many AnalysisRequests.
   * @example
   * // Create many AnalysisRequests
   * const analysisRequest = await prisma.analysisRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AnalysisRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, AnalysisRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AnalysisRequests and returns the data saved in the database.
   * @param {AnalysisRequestCreateManyAndReturnArgs} args - Arguments to create many AnalysisRequests.
   * @example
   * // Create many AnalysisRequests
   * const analysisRequest = await prisma.analysisRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AnalysisRequests and only return the `id`
   * const analysisRequestWithIdOnly = await prisma.analysisRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AnalysisRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AnalysisRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AnalysisRequest.
   * @param {AnalysisRequestDeleteArgs} args - Arguments to delete one AnalysisRequest.
   * @example
   * // Delete one AnalysisRequest
   * const AnalysisRequest = await prisma.analysisRequest.delete({
   *   where: {
   *     // ... filter to delete one AnalysisRequest
   *   }
   * })
   * 
   */
  delete<T extends AnalysisRequestDeleteArgs>(args: Prisma.SelectSubset<T, AnalysisRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AnalysisRequest.
   * @param {AnalysisRequestUpdateArgs} args - Arguments to update one AnalysisRequest.
   * @example
   * // Update one AnalysisRequest
   * const analysisRequest = await prisma.analysisRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AnalysisRequestUpdateArgs>(args: Prisma.SelectSubset<T, AnalysisRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AnalysisRequests.
   * @param {AnalysisRequestDeleteManyArgs} args - Arguments to filter AnalysisRequests to delete.
   * @example
   * // Delete a few AnalysisRequests
   * const { count } = await prisma.analysisRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AnalysisRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, AnalysisRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnalysisRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AnalysisRequests
   * const analysisRequest = await prisma.analysisRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AnalysisRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, AnalysisRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnalysisRequests and returns the data updated in the database.
   * @param {AnalysisRequestUpdateManyAndReturnArgs} args - Arguments to update many AnalysisRequests.
   * @example
   * // Update many AnalysisRequests
   * const analysisRequest = await prisma.analysisRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AnalysisRequests and only return the `id`
   * const analysisRequestWithIdOnly = await prisma.analysisRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AnalysisRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AnalysisRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AnalysisRequest.
   * @param {AnalysisRequestUpsertArgs} args - Arguments to update or create a AnalysisRequest.
   * @example
   * // Update or create a AnalysisRequest
   * const analysisRequest = await prisma.analysisRequest.upsert({
   *   create: {
   *     // ... data to create a AnalysisRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AnalysisRequest we want to update
   *   }
   * })
   */
  upsert<T extends AnalysisRequestUpsertArgs>(args: Prisma.SelectSubset<T, AnalysisRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AnalysisRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRequestCountArgs} args - Arguments to filter AnalysisRequests to count.
   * @example
   * // Count the number of AnalysisRequests
   * const count = await prisma.analysisRequest.count({
   *   where: {
   *     // ... the filter for the AnalysisRequests we want to count
   *   }
   * })
  **/
  count<T extends AnalysisRequestCountArgs>(
    args?: Prisma.Subset<T, AnalysisRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AnalysisRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AnalysisRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AnalysisRequestAggregateArgs>(args: Prisma.Subset<T, AnalysisRequestAggregateArgs>): Prisma.PrismaPromise<GetAnalysisRequestAggregateType<T>>

  /**
   * Group by AnalysisRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AnalysisRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AnalysisRequestGroupByArgs['orderBy'] }
      : { orderBy?: AnalysisRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AnalysisRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAnalysisRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AnalysisRequest model
 */
readonly fields: AnalysisRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AnalysisRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AnalysisRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AnalysisRequest model
 */
export interface AnalysisRequestFieldRefs {
  readonly id: Prisma.FieldRef<"AnalysisRequest", 'String'>
  readonly profileUrl: Prisma.FieldRef<"AnalysisRequest", 'String'>
  readonly status: Prisma.FieldRef<"AnalysisRequest", 'String'>
  readonly createdAt: Prisma.FieldRef<"AnalysisRequest", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AnalysisRequest", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AnalysisRequest findUnique
 */
export type AnalysisRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * Filter, which AnalysisRequest to fetch.
   */
  where: Prisma.AnalysisRequestWhereUniqueInput
}

/**
 * AnalysisRequest findUniqueOrThrow
 */
export type AnalysisRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * Filter, which AnalysisRequest to fetch.
   */
  where: Prisma.AnalysisRequestWhereUniqueInput
}

/**
 * AnalysisRequest findFirst
 */
export type AnalysisRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * Filter, which AnalysisRequest to fetch.
   */
  where?: Prisma.AnalysisRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisRequests to fetch.
   */
  orderBy?: Prisma.AnalysisRequestOrderByWithRelationInput | Prisma.AnalysisRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnalysisRequests.
   */
  cursor?: Prisma.AnalysisRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalysisRequests.
   */
  distinct?: Prisma.AnalysisRequestScalarFieldEnum | Prisma.AnalysisRequestScalarFieldEnum[]
}

/**
 * AnalysisRequest findFirstOrThrow
 */
export type AnalysisRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * Filter, which AnalysisRequest to fetch.
   */
  where?: Prisma.AnalysisRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisRequests to fetch.
   */
  orderBy?: Prisma.AnalysisRequestOrderByWithRelationInput | Prisma.AnalysisRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnalysisRequests.
   */
  cursor?: Prisma.AnalysisRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalysisRequests.
   */
  distinct?: Prisma.AnalysisRequestScalarFieldEnum | Prisma.AnalysisRequestScalarFieldEnum[]
}

/**
 * AnalysisRequest findMany
 */
export type AnalysisRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * Filter, which AnalysisRequests to fetch.
   */
  where?: Prisma.AnalysisRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisRequests to fetch.
   */
  orderBy?: Prisma.AnalysisRequestOrderByWithRelationInput | Prisma.AnalysisRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AnalysisRequests.
   */
  cursor?: Prisma.AnalysisRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalysisRequests.
   */
  distinct?: Prisma.AnalysisRequestScalarFieldEnum | Prisma.AnalysisRequestScalarFieldEnum[]
}

/**
 * AnalysisRequest create
 */
export type AnalysisRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * The data needed to create a AnalysisRequest.
   */
  data: Prisma.XOR<Prisma.AnalysisRequestCreateInput, Prisma.AnalysisRequestUncheckedCreateInput>
}

/**
 * AnalysisRequest createMany
 */
export type AnalysisRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AnalysisRequests.
   */
  data: Prisma.AnalysisRequestCreateManyInput | Prisma.AnalysisRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AnalysisRequest createManyAndReturn
 */
export type AnalysisRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * The data used to create many AnalysisRequests.
   */
  data: Prisma.AnalysisRequestCreateManyInput | Prisma.AnalysisRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AnalysisRequest update
 */
export type AnalysisRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * The data needed to update a AnalysisRequest.
   */
  data: Prisma.XOR<Prisma.AnalysisRequestUpdateInput, Prisma.AnalysisRequestUncheckedUpdateInput>
  /**
   * Choose, which AnalysisRequest to update.
   */
  where: Prisma.AnalysisRequestWhereUniqueInput
}

/**
 * AnalysisRequest updateMany
 */
export type AnalysisRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AnalysisRequests.
   */
  data: Prisma.XOR<Prisma.AnalysisRequestUpdateManyMutationInput, Prisma.AnalysisRequestUncheckedUpdateManyInput>
  /**
   * Filter which AnalysisRequests to update
   */
  where?: Prisma.AnalysisRequestWhereInput
  /**
   * Limit how many AnalysisRequests to update.
   */
  limit?: number
}

/**
 * AnalysisRequest updateManyAndReturn
 */
export type AnalysisRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * The data used to update AnalysisRequests.
   */
  data: Prisma.XOR<Prisma.AnalysisRequestUpdateManyMutationInput, Prisma.AnalysisRequestUncheckedUpdateManyInput>
  /**
   * Filter which AnalysisRequests to update
   */
  where?: Prisma.AnalysisRequestWhereInput
  /**
   * Limit how many AnalysisRequests to update.
   */
  limit?: number
}

/**
 * AnalysisRequest upsert
 */
export type AnalysisRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * The filter to search for the AnalysisRequest to update in case it exists.
   */
  where: Prisma.AnalysisRequestWhereUniqueInput
  /**
   * In case the AnalysisRequest found by the `where` argument doesn't exist, create a new AnalysisRequest with this data.
   */
  create: Prisma.XOR<Prisma.AnalysisRequestCreateInput, Prisma.AnalysisRequestUncheckedCreateInput>
  /**
   * In case the AnalysisRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AnalysisRequestUpdateInput, Prisma.AnalysisRequestUncheckedUpdateInput>
}

/**
 * AnalysisRequest delete
 */
export type AnalysisRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
  /**
   * Filter which AnalysisRequest to delete.
   */
  where: Prisma.AnalysisRequestWhereUniqueInput
}

/**
 * AnalysisRequest deleteMany
 */
export type AnalysisRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnalysisRequests to delete
   */
  where?: Prisma.AnalysisRequestWhereInput
  /**
   * Limit how many AnalysisRequests to delete.
   */
  limit?: number
}

/**
 * AnalysisRequest without action
 */
export type AnalysisRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRequest
   */
  select?: Prisma.AnalysisRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRequest
   */
  omit?: Prisma.AnalysisRequestOmit<ExtArgs> | null
}
